### ISSUE TITLE
[Feature][scaleph-ui-react] more seatunnel connector support in new dag version

### ISSUE THREAD

**Issue by gleiyu** [flowerfine/scaleph#260]
### Already searched before asking?

- [X] I had searched in the [feature](https://github.com/flowerfine/scaleph/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Usage Scenario

more seatunnel connector support in new dag version
- seatunnel connector v2 https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2
- how to connector in scaleph 

## source

- [x] [Feature] [scaleph-plugins] Fake source #269 
- [x] #281
- [x] [Feature] [scaleph-plugins] FtpFile source #275 
- [x] #282
- [x] [Feature] [scaleph-plugins] HdfsFile source #271 
- [x] #283
- [x] #284
- [x] [Feature] [scaleph-plugins] Hudi source #262 
- [x] [Feature] [scaleph-plugins] Icebreg source #264 
- [x] #285
- [x] [Feature] [scaleph-plugins] jdbc source
- [x] #286
- [x] [Feature] [scaleph-plugins] LocalFile source #266 
- [x] #287
- [x] #288
- [ ] #289
- [x] #290
- [x] #291
- [x] #292

## sink
- [ ] #293
- [x] #294
- [ ] #295
- [x] #277
- [x] #296
- [x] #297
- [x] #298
- [x] #299
- [x] #300
- [x] [Feature] [scaleph-plugins] FtpFile sink #275 
- [x] #301
- [x] [Feature] [scaleph-plugins] HdfsFile sink #275 
- [x] #302
- [x] #303
- [x] #304
- [x] [Feature] [scaleph-plugins] Jdbc sink
- [x] #305
- [x] [Feature] [scaleph-plugins] LocalFile sink #266 
- [x] #306
- [x] #307
- [x] #308
- [ ] #309
- [x] #310
- [x] #280
- [x] #278
- [x] #279

### Are you willing to submit a PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/)

**Comment by kalencaya** [comment]
I'm working on hudi source #261

**Comment by kalencaya** [comment]
> I'm working on hudi source #261

done

**Comment by kalencaya** [comment]
Begin to work on iceberg source #263

**Comment by lizu18xz** [comment]
I'm working on fake source

**Comment by kalencaya** [comment]
> Begin to work on iceberg source #263

done

**Comment by kalencaya** [comment]
Begin to work on local file source for #265 and sink for #267

**Comment by kalencaya** [comment]
> Begin to work on local file source for #265 and sink for #267

done

**Comment by kalencaya** [comment]
support ftp file connector #270

**Comment by kalencaya** [comment]
> support ftp file connector #270

done

**Comment by kalencaya** [comment]
support oss file connector

**Comment by kalencaya** [comment]
> support oss file connector

done

**Comment by kalencaya** [comment]
support http file connector

**Comment by kalencaya** [comment]
> support http file connector

done

**Comment by kalencaya** [comment]
support wechat connector

**Comment by kalencaya** [comment]
> support wechat connector

done

**Comment by kalencaya** [comment]
As we already have finished the most connectors, close this issue
