### ISSUE TITLE
[Feature][scaleph-core-di] SeaTunnel v2 connectors submit

### ISSUE THREAD

**Issue by kalencaya** [flowerfine/scaleph#343]
### Description

submit SeaTunnel v2 connectors tasks

### Tasks

- [x] build SeaTunnel v2 connectors conf file
- [x] resource file download framework and local cache
- [x] seatunnel job step form
- [x] seatunnel connector resource support
- [x] seatunnel connector upload support
- [x] seatunnel job submit
- [x] seatunnnel jdbc connector plugin
- [ ] seatunnel fake connector form replace value by select form item for schema field
- [ ] seatunnel and flink release base image
- [ ] seatunnel job schema refactor

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/)
