### ISSUE TITLE
[Feature][scaleph-meta] refactor DataSource web

### ISSUE THREAD

**Issue by kalencaya** [flowerfine/scaleph#372]
### Already searched before asking?

- [X] I had searched in the [feature](https://github.com/flowerfine/scaleph/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Usage Scenario

add DataSource on the top navbar and refactor DataSource web

### Description

data source category. 
- [ ] add
- [ ] update
- [ ] delete
- [ ] add or remove data source type relation

data source
- [ ] update

data source form
- [x] MySQL
- [x] Oracle
- [x] PostgreSQL
- [x] SQLServer
- [x] DmDB
- [x] GBase8a
- [x] Greenplum
- [x] Phoenix
- [x] Redis
- [x] Elasticsearch
- [ ] Solr
- [x] MongoDB
- [ ] TiDB
- [x] Kafka
- [x] Pulsar
- [x] DataHub
- [x] FTP
- [ ] SFTP
- [x] HDFS
- [x] OSS
- [x] S3
- [x] Hive
- [x] ClickHouse
- [ ] Hudi
- [ ] Iceberg
- [x] Kudu
- [x] IoTDB
- [x] Neo4j
- [x] InfluxDB
- [ ] HBase
- [ ] Impala
- [ ] Doris
- [ ] Kylin
- [ ] Druid
- [x] Socket
- [x] Http
- [ ] Sentry
- [ ] Email

### Are you willing to submit a PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/)
