### ISSUE TITLE
[Feature] flink sql gateway service

### ISSUE THREAD

**Issue by kalencaya** [flowerfine/scaleph#375]
### Already searched before asking?

- [X] I had searched in the [feature](https://github.com/flowerfine/scaleph/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Usage Scenario

support flink sql web studio function

#### Core Concepts

flink catalog

- catalog
- database
- table
- udf

sql service

- sql scripts
- connectors

sql gateway

- session. open, close, config
- operation. submit, cancel, close, resultset

flink cluster

- resource provider. standalone, yarn, kubernetes
- deploy mode. application, session, per-job(deprecated)

#### Flink Components

- flink-sql-gateway

#### RoadMap

catalog

- [ ] [flink catalog service](https://github.com/flowerfine/scaleph/issues/410)

sql service

- [ ] sql scripts. list, get, insert, update, delete; version management;

flink-sql-gateway
- [x] flink-sql-gateway usage. include deploy flink-sql-gateway on yarn or kubernetes, flink-sql-gateway http service
- [x] flink-sql-gateway rest api on flinkful
- [ ] flink-sql-gateway resource
- [ ] flink-sql-gateway http service

scaleph-ui-react
- [ ] [web sql editor](https://opensumi.com/zh/docs/integrate/quick-start/lite)

### Are you willing to submit a PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/)
